sudo: required
dist: trusty

os:
  - osx
  - linux

osx_image: xcode9.0

addons:
  apt:
    packages:
    - build-essential
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev
  artifacts:
    paths:
      - $(ls ./dist/*.AppImage | tr "\n" ":")
      - $(ls ./dist/*.deb | tr "\n" ":")
      - $(ls ./dist/*.snap | tr "\n" ":")
      - $(ls ./dist/*.dmg | tr "\n" ":")
      - $(ls ./dist/*.zip | tr "\n" ":")
      - $(ls ./dist/*.dmg.blockmap | tr "\n" ":")
      - $(ls ./dist/github/*.json | tr "\n" ":")
      - $(ls ./dist/github/*.yml | tr "\n" ":")
      - $(ls ./dist/*.yml | tr "\n" ":")
      - $(ls ./dist/mac/*.yml | tr "\n" ":")
      - $(ls ./dist/linux/*.yml | tr "\n" ":")

language: node_js
node_js:
- '6'

before_install:
  - ./scripts/travis-xvfb.sh
  - npm install -g gulp
  - npm install

cache:
  directories:
    - node_modules
    - app/node_modules
    - ~/.cache

script:
  - npm run travis
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ls
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "./scripts/install-apt-dependencies.sh && electron-builder -l"
        ./scripts/rename-zip-files.sh linux
    else
      # mac travis build run only windows x32 bit
      electron-builder -w
      ./scripts/rename-zip-files.sh ia32
      electron-builder -m
      ./scripts/rename-zip-files.sh mac
    fi

  # log out /dist files might be useful to know
  # what files are uploaded
  - mv dist/zips/* dist/
  - rm -rf dist/zips
  - ls dist

notifications:
  webhooks:
    urls:
      - https://zulip.org/zulipbot/travis
    on_success: always
    on_failure: always
